BuildEnvironments:
  unix:
    InstallPath:
      java: /home/alice/data/workspace/env/java
      mysql: null
      nacos: null
    PackagePath:
      java: /home/alice/data/workspace/package/jdk-8u202-linux-x64.tar.gz
      mysql: null
      nacos: null
  win:
    InstallPath:
      java: D:\data\Development\env\run\java
      mysql: D:\data\Development\env\run\mysql
      nacos: null
    PackagePath:
      java: D:\data\Development\package\Java1.8.202.zip
      mysql: D:\data\Development\package\MySQL5.7.32.zip
      nacos: null
RunEnvironment:
  unix:
    java: /home/alice/data/workspace/env/java/jdk1.8.0_202/bin/java
#  win:
#    java: D:\develops\WorkSpace\runnet\environment\java\jdk\bin\java.exe
